# src/EBM/GDPBundle/Resources/config/routing.yml

# Vue Dashboard des projets encadrant
ebmgdp_insight_dash:
    path:     insight
    defaults: { _controller: EBMGDPBundle:Insight:index }

ebmgdp_insight_documenttypeproject_list:
    path:     insight/documenttypeprojectlist
    defaults: { _controller: EBMGDPBundle:Insight:documentTypeProjectList }

ebmgdp_insight_documenttypeproject_view:
    path:     insight/documenttypeproject/{id}
    defaults: { _controller: EBMGDPBundle:Insight:documentTypeProjectview }
    requirements:
                 id: \d+
ebmgdp_insight_documenttypeproject_index:
    path:     insight/documenttypeproject
    defaults: { _controller: EBMGDPBundle:DocumentTypeProject:index }

ebmgdp_insight_documenttypeproject_new:
    path:     insight/documenttypeproject/new
    defaults: { _controller: EBMGDPBundle:DocumentTypeProject:new }

ebmgdp_insight_documenttypeproject_show:
    path:     insight/documenttypeproject/show/{id}
    defaults: { _controller: EBMGDPBundle:DocumentTypeProject:show }
    requirements:
             id: \d+

ebmgdp_insight_documenttypeproject_edit:
   path:     insight/documenttypeproject/{id}/edit
   defaults: { _controller: EBMGDPBundle:DocumentTypeProject:edit }
   requirements:
            id: \d+

ebmgdp_insight_documenttypeproject_delete:
   path:     insight/documenttypeproject/{id}/delete
   defaults: { _controller: EBMGDPBundle:DocumentTypeProject:delete }
   requirements:
            id: \d+

# Vue liste tache d'un projet
ebmgdp_projecttasks:
    path:     project/{code}/tasks
    defaults: { _controller: EBMGDPBundle:Task:index }

# Vue liste tache archiv√©e d'un projet
ebmgdp_projecttasksarchived:
    path:     project/{code}/tasks/archived
    defaults: { _controller: EBMGDPBundle:Task:indexArchived }

# Ajout d'une tache
ebmgdp_task_add:
    path:     project/{code}/tasks/add
    defaults: { _controller: EBMGDPBundle:Task:addTask }

# Edit d'une tache
ebmgdp_task_edit:
    path:     project/{code}/task/{id}/edit
    defaults: { _controller: EBMGDPBundle:Task:editTask }
    requirements:
             id: \d+

# Ajout d'un livrable obligatoire
ebmgdp_deliverable_add_mandatory:
    path:     project/{code}/deliverables/addMandatory
    defaults: { _controller: EBMGDPBundle:Deliverable:addMandatory }

# Ajout d'un livrable
ebmgdp_deliverable_add:
    path:     project/{code}/deliverables/add
    defaults: { _controller: EBMGDPBundle:Deliverable:add }

# Archivage d'une tache
ebmgdp_task_archived:
   path:     project/{code}/task/{id}/archived
   defaults: { _controller: EBMGDPBundle:Task:archivedTask }
   requirements:
            id: \d+

# Vue d'une tache
ebmgdp_task:
    path:     project/{code}/task/{id}
    defaults: { _controller: EBMGDPBundle:Task:view }

# Vue livrables d'un projet
ebmgdp_projectdeliverables:
    path:     project/{code}/deliverables
    defaults: { _controller: EBMGDPBundle:Project:viewDeliverables }

# Vue d'un livrable
ebmgdp_deliverable:
    path:     project/{code}/deliverable/{id}
    defaults: { _controller: EBMGDPBundle:Deliverable:index }

# Vue du calendrier
ebmgdp_calendar:
    path:     project/{code}/calendar
    defaults: { _controller: EBMGDPBundle:Calendar:viewCalendar }

# Route Chager Status Tache
ebmgdp_task_edit_status:
    path:     project/{code}/task/status/edit
    defaults: { _controller: EBMGDPBundle:Task:editTaskStatus }

# Ajout d'un commentaire
ebmgdp_task_comment_add:
    path:     project/{code}/task/{id}/comment/add
    defaults: { _controller: EBMGDPBundle:Comment:addCommentOnTask }

# Edit d'un commentaire
ebmgdp_task_comment_edit:
    path:     project/{code}/task/{id}/comment/{idc}/edit
    defaults: { _controller: EBMGDPBundle:Comment:editCommentOnTask }
    requirements:
             idc: \d+
             id: \d+

# Suppression d'un commentaire task
ebmgdp_task_comment_delete:
   path:     project/{code}/task/{id}/comment/{idc}/delete
   defaults: { _controller: EBMGDPBundle:Comment:deleteCommentOnTask }
   requirements:
            idc: \d+
            id: \d+

# Ajout d'un commentaire livrable
ebmgdp_deliverable_comment_add:
    path:     project/{code}/deliverable/{id}/comment/add
    defaults: { _controller: EBMGDPBundle:Comment:addCommentOnDeliverable }

# Edit d'un commentaire livrable
ebmgdp_deliverable_comment_edit:
    path:     project/{code}/deliverable/{id}/comment/{idc}/edit
    defaults: { _controller: EBMGDPBundle:Comment:editCommentOnDeliverable }
    requirements:
             idc: \d+
             id: \d+

# Suppression d'un commentaire livrable
ebmgdp_deliverable_comment_delete:
   path:     project/{code}/deliverable/{id}/comment/{idc}/delete
   defaults: { _controller: EBMGDPBundle:Comment:deleteCommentOnDeliverable }
   requirements:
            idc: \d+
            id: \d+
